title = "Default Title"
description = "Default Description"

[profile]
name = "Default Name"
icon_url = "https://via.placeholder.com/200"
introduction = """
私はフロントエンドおよびバックエンドの開発に10年以上の経験があります。
              JavaScript、React、Node.jsを主に使用しています。新しいプロジェクトに挑戦することが大好きで、
              常に最新の技術を学び続けています。"""

[[profile.work_experiences]]
company = "Default Company"
active = true

[[profile.work_experiences.projects]]
name = "Default Project"
period = "2020/01 - 2020/12"
description = "Default Description.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
tags = ["Default Tag"]

[[profile.certificates]]
name = "Default Certificate"
date = "2020/12"
#description = "Default Description"
is_expired = false
url = "https://example.com"

[[profile.certificates]]
name = "Default Certificate"
date = "2020/12"
#description = "Default Description"
is_expired = false
url = "https://example.com"

[header]
title = "Default Header Title"

[[header.links]]
name = "Home"
url = "/"

[[header.links]]
name = "About"
url = "/about"

[[header.links]]
name = "Articles"
url = "/articles"

[footer]
name = "John Akiyama"

[rss]
urls = ["https://zenn.dev/ucpr/feed?include_scraps=1", "https://ucpr.hatenablog.com/rss"]

[google_analytics]
tracking_id = "UA-123456789-0"
